In [ ]:
import numpy as pd

In [ ]:
a=pd.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
result=a+a
result

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
mult=a*a
mult

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
min=a-a
min

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
div=a/a
div

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
z=a-1
z

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
c=a*2
c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
s=a/2
s

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
new=pd.arange(1,10)
new

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
divi=new/new
divi

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])